/* Include specific libraries */
#include <compiler/info/info.h>

/* Prints current Lena's version */
void version(void) {
    lccol(LC_COLOR_RED, LC_COLOR_BLACK);
    lcout(X("Lena compiler "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("version "));
    lccol(LC_COLOR_YELLOW, LC_COLOR_BLACK);
    lcout(LENA_VERSION_STR);
}

/* Static buffer for C version string */
lc c_version_buffer[65];

/* Prints full current Lena's version */
void version_extented(void) {
    version();
    lccol(LC_COLOR_RED, LC_COLOR_BLACK);
    lcout(X("\n\n"));

    lccol(LC_COLOR_YELLOW, LC_COLOR_BLACK);
    lcout(X("Build information\n\n"));

    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("Compiler: "));

    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(LENA_C_COMPILER_STR);

    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("\nC language standard: "));

    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lsi64dec(c_version_buffer, (li64)(__STDC_VERSION__));
    lcout(c_version_buffer);

    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("\n\nTarget operating system: "));

    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(LENA_BUILD_OS_STR);

    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("\nTarget architecture: "));

    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(LENA_BUILD_ARCH_STR);

    lccol(LC_COLOR_YELLOW, LC_COLOR_BLACK);
    lcout(X("\n\nBuild time: "));

    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(LENA_BUILD_TIME_STR);
}

/* Prints Lena's license */
void license(void) {
    lccol(LC_COLOR_RED, LC_COLOR_BLACK);
    lcout(X("Lena Compiler License\n\n"));

    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("The Lena compiler is licensed under the GNU General Public License version 3 (GPL-3.0).\n\
This license guarantees end users the freedom to run, study, share, and modify the software.\n\n"));

    lccol(LC_COLOR_GREEN, LC_COLOR_BLACK);
    lcout(X("GPL-3.0 License\n"));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("Copyright (c) 2024 The Lena Programming language\n\n\
This program is free software: you can redistribute it and/or modify\n\
it under the terms of the GNU General Public License as published by\n\
the Free Software Foundation, either version 3 of the License, or\n\
(at your option) any later version.\n\n\
but WITHOUT ANY WARRANTY; without even the implied warranty of\n\
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\n\
GNU General Public License for more details.\n\n\
You should have received a copy of the GNU General Public License\n\
along with this program. If not, see "));
    lccol(LC_COLOR_YELLOW, LC_COLOR_BLACK);
    lcout(X("<https://www.gnu.org/licenses/>"));

    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X(".\n\nFor the full license text, please refer to the "));
    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("LICENSE "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("file included with this software.\n"));
}

/* Prints help message */

void help_about(void) {
    lccol(LC_COLOR_RED, LC_COLOR_BLACK);
    lcout(X("Lena Compiler\n\n"));

    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("The Lena compiler is a powerful tool designed for the Lena programming language,\n\
a high-performance system language that combines the efficiency of lower-level\n\
languages with the ease of use found in higher-level languages.\n\
Lena is specifically designed to run outside the main operating system,\n\
allowing it to access nearly all computer resources and achieve performance\n\
levels comparable to machine code or assembler. This makes Lena an excellent choice\n\
for developing optimized and resource-intensive applications."));
}

void help_formats(void) {
    lccol(LC_COLOR_YELLOW, LC_COLOR_BLACK);
    lcout(X("File Formats\n"));
    
    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("- .e\t: "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("This is the bytecode file generated by the Lena compiler.\n"));

    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("- .le\t: "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("This is the source code file for the Lena programming language.\n"));

    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("- .na\t: "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("This file format is used for storing non-abstract representations of Lena programs, often containing decoded bytecode.\n"));

    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("- .exe\t: "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("The executable file format generated by the Lena compiler for running applications."));
}

void help_flags(void) {
    lccol(LC_COLOR_YELLOW, LC_COLOR_BLACK);
    lcout(X("Compilation Flags\n"));

    lccol(LC_COLOR_GREEN, LC_COLOR_BLACK);
    lcout(X("--version\t: "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("Displays the current version of the Lena compiler.\n"));

    lccol(LC_COLOR_GREEN, LC_COLOR_BLACK);
    lcout(X("-v\t\t: "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("A shorthand for --version, displaying the compiler's version information.\n"));

    lccol(LC_COLOR_GREEN, LC_COLOR_BLACK);
    lcout(X("--help\t\t: "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("Provides a detailed help message, including usage instructions and available flags.\n"));

    lccol(LC_COLOR_GREEN, LC_COLOR_BLACK);
    lcout(X("--license\t: "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("Shows the licensing information for the Lena compiler.\n"));

    lccol(LC_COLOR_GREEN, LC_COLOR_BLACK);
    lcout(X("--non-abstract\t: "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("Generates a bytecode map for the compiled program, providing a detailed view of the bytecode structure.\n"));

    lccol(LC_COLOR_GREEN, LC_COLOR_BLACK);
    lcout(X("-o\t\t: "));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("Specifies the output file name for the compiled program."));
}

void help_usage(void) {
    lccol(LC_COLOR_YELLOW, LC_COLOR_BLACK);
    lcout(X("Usage Examples\n"));

    lccol(LC_COLOR_RED, LC_COLOR_BLACK);
    lcout(X("lena "));
    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("main.le "));
    lccol(LC_COLOR_GREEN, LC_COLOR_BLACK);
    lcout(X("-o "));
    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("app.e "));
    lccol(LC_COLOR_GREEN, LC_COLOR_BLACK);
    lcout(X("--non-abstract\n"));
    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("This command compiles main.le into a bytecode file app.e and generates a non-abstract bytecode map.\n\n"));

    lccol(LC_COLOR_RED, LC_COLOR_BLACK);
    lcout(X("lena "));
    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("main.le "));
    lccol(LC_COLOR_GREEN, LC_COLOR_BLACK);
    lcout(X("-o "));
    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("app "));


    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("or "));

    lccol(LC_COLOR_RED, LC_COLOR_BLACK);
    lcout(X("lena "));
    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("main.le "));
    lccol(LC_COLOR_GREEN, LC_COLOR_BLACK);
    lcout(X("-o "));
    lccol(LC_COLOR_CYAN, LC_COLOR_BLACK);
    lcout(X("app.exe\n"));

    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("This command compiles main.le into a executable file app (.exe)."));
}

void help_about_she(void) {
    lccol(LC_COLOR_YELLOW, LC_COLOR_BLACK);
    lcout(X("SHE Executor\n"));

    lccol(LC_COLOR_WHITE, LC_COLOR_BLACK);
    lcout(X("The SHE (Software-Clonable Hypervisor Executor) is a separate application that operates independently of the Lena compiler. It functions as an external device on Windows and as a kernel submodule on Linux. SHE provides Lena applications with unparalleled access to system resources and exceptional performance, ensuring that Lena programs run efficiently and securely, with advanced memory and safety checks.\n"));
}

void help(void) {
    help_about();
    lcout(X("\n\n"));
    help_formats();
    lcout(X("\n\n"));
    help_flags();
    lcout(X("\n\n"));
    help_usage();
    lcout(X("\n\n"));
    help_about_she();
}